### ISSUE TITLE
[Feature request] Xbox Series X controllers

### ISSUE THREAD

**Issue by benderlemagnificent** [qibinc/JoyMapperSilicon#4]
The new MacOS 11.3 supports the current gen (PS5 and XBSX) gamepads but JoyMapper isn't recognizing my Xbox controller even as some games and most emulators do. It would be great if JoyMapper could work with the Series X gamepad so that older titles with no current support could be played.

**Comment by qibinc** [comment]
Hi @benderlemagnificent ,

We apologize this will not be possible for this project in the future. This whole project is based on Nintendo's SDK which is why it's called **Joy**MapperSilicon. Please use other alternatives such as Enjoyable/Enjoy2
