### ISSUE TITLE
PS4  DualShock controller support?

### ISSUE THREAD

**Issue by unphased** [qibinc/JoyMapperSilicon#6]
Monterey, M1 Max here. 

It seems to connect to macos and works in Steam Big picture, but does not respond in game (overcooked 2). 

I will use nintendo pro controller with this app (as it has the same behavior of only working in Big Picture and not in game, so mapping buttons to keyboard would be the way to go for the time being), Nintendo seems to be the only controllers supported? Maybe the name can be more clear about this. I do see that the first sentence in readme specifies this but I didn't actually read it.

**Comment by Kickflipkid687** [comment]
Yeah, I can use my Xbox Series X / PS4 controller on M1 Mac Pro, Monterey with like Dolphin for example, so they DO work... but this app doesn't detect the controllers at all for some reason...

**Comment by MCMi460** [comment]
Maybe I'm wrong about this one, but isn't this app supposed to be specifically for Nintendo Joycons and Pro controllers? I don't think it's supposed to support an Xbox or Play Station controller.

**Comment by Kickflipkid687** [comment]
Yeah, you are right... I didn't think about the name at first, heh.   I may start to learn Xcode and see if i can make something myself... we will see how that goes... I know C# / C++ a tiny bit / WPF / Python.

**Comment by qibinc** [comment]
Thanks @MCMi460 for providing the correct answer
